---
- name: Playbook to get information about a file- present/absent
  hosts: all
  become: true
  gather_facts: false
  tasks: 
   - name: check for a file
     stat:
       path: /etc/password
     register: output
   - name: print the output
     debug:
       var: output
...
